[package]
name = "ethernet-benchmark"
version = "0.1.1"
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.workspaces]
independent = true

[dependencies]
luwen = { workspace = true }
rand = "0.8.5"
