[package]
name = "luwen-def"
version = "0.2.1"
description = "Common dependencies shared by all crates based on luwen"
edition = "2021"
license = "Apache-2.0"

[dependencies]
thiserror = { workspace = true }

[package.metadata.workspaces]
independent = true
